-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

DROP TABLE IF EXISTS "employees_roles";
DROP TABLE IF EXISTS "employees";
DROP TABLE IF EXISTS "roles";
DROP TABLE IF EXISTS "departments";

CREATE SEQUENCE seq_depart_id
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS "departments"
(
    depart_id bigint DEFAULT nextval('seq_depart_id') NOT NULL,
    depart_name character varying(50) NOT NULL,
    CONSTRAINT "departments_pkey" PRIMARY KEY (depart_id)
);

CREATE TABLE IF NOT EXISTS "employees_roles"
(
    emp_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT "employees_roles_pkey" PRIMARY KEY (emp_id, role_id)
);

CREATE SEQUENCE seq_emp_id
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS "employees"
(
    emp_id bigint DEFAULT nextval('seq_emp_id') NOT NULL,
    name character varying(30) NOT NULL,
    surname character varying(30) NOT NULL,
    sex character(1) NOT NULL,
    birth_date date NOT NULL,
    pass_no character varying(12),
    pass_valid date,
    depart_id bigint NOT NULL,
    CONSTRAINT "employees_pkey" PRIMARY KEY (emp_id)
);

CREATE SEQUENCE seq_role_id
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS "roles"
(
    role_id bigint DEFAULT nextval('seq_role_id')  NOT NULL,
    role character varying(30) NOT NULL,
    CONSTRAINT "roles_pkey" PRIMARY KEY (role_id)
);

ALTER TABLE IF EXISTS "employees_roles"
    ADD CONSTRAINT "employees_roles_fkey_emp" FOREIGN KEY (emp_id)
    REFERENCES "employees" (emp_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_employees_roles_fkey_emp"
    ON "employees_roles"(emp_id);

ALTER TABLE IF EXISTS "employees_roles"
    ADD CONSTRAINT "employees_roles_fkey_role" FOREIGN KEY (role_id)
    REFERENCES "roles" (role_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_employees_roles_fkey_role"
    ON "employees_roles"(role_id);

ALTER TABLE IF EXISTS "employees"
    ADD CONSTRAINT "employees_fkey_depart" FOREIGN KEY (depart_id)
    REFERENCES "departments" (depart_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_employees_fkey_depart"
    ON "employees"(depart_id);
