-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
CREATE TABLE IF NOT EXISTS "tblDepartments"
(
    depart_id integer NOT NULL,
    depart_name character varying(50) NOT NULL,
    CONSTRAINT "tblDepartments_pkey" PRIMARY KEY (depart_id)
);

CREATE TABLE IF NOT EXISTS "tblEmployeeRoles"
(
    emp_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT "tblEmployeeRoles_pkey" PRIMARY KEY (emp_id, role_id)
);

CREATE TABLE IF NOT EXISTS "tblEmployees"
(
    emp_id integer NOT NULL,
    name character varying(30) NOT NULL,
    surname character varying(30) NOT NULL,
    sex character(1) NOT NULL,
    birth_date date NOT NULL,
    pass_no character varying(12),
    pass_valid date,
    depart_id integer NOT NULL,
    CONSTRAINT "tblEmployees_pkey" PRIMARY KEY (emp_id)
);

CREATE TABLE IF NOT EXISTS "tblRoles"
(
    role_id integer NOT NULL,
    role character varying(30) NOT NULL,
    CONSTRAINT "tblRoles_pkey" PRIMARY KEY (role_id)
);

ALTER TABLE IF EXISTS "tblEmployeeRoles"
    ADD CONSTRAINT "tblEmployeeRoles_fkey_emp" FOREIGN KEY (emp_id)
    REFERENCES "tblEmployees" (emp_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_tblEmployeeRoles_fkey_emp"
    ON "tblEmployeeRoles"(emp_id);


ALTER TABLE IF EXISTS "tblEmployeeRoles"
    ADD CONSTRAINT "tblEmployeeRoles_fkey_role" FOREIGN KEY (role_id)
    REFERENCES "tblRoles" (role_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_tblEmployeeRoles_fkey_role"
    ON "tblEmployeeRoles"(role_id);


ALTER TABLE IF EXISTS "tblEmployees"
    ADD CONSTRAINT "tblEmployees_fkey_depart" FOREIGN KEY (depart_id)
    REFERENCES "tblDepartments" (depart_id)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_tblEmployees_fkey_depart"
    ON "tblEmployees"(depart_id);
